### ISSUE TITLE
POS tagging description

### ISSUE THREAD

**Issue by baominhlt** [undertheseanlp/NLP-Vietnamese-progress#23]
Cho em hỏi về description của các nhãn trong các bài toán POS và Denpendency parser được không ạ?

**Comment by ngoquanghuy99** [comment]
Bạn tham khảo nhé: [paper](http://www.lrec-conf.org/proceedings/lrec2016/pdf/95_Paper.pdf)
cc @rain1024

**Comment by baominhlt** [comment]
Em nhận được rồi ạ. Em cám ơn.
