### ISSUE TITLE
POS tagging

### ISSUE THREAD

**Issue by TQuy** [undertheseanlp/NLP-Vietnamese-progress#5]
The no.1 accuracy in the leader board should be 93.52 instead of 96.30 according to the corresponding paper

**Comment by rain1024** [comment]
@TQuy It's corrected. Thank you so much ^.^

**Comment by TQuy** [comment]
We really appreciate your effort

**Comment by rain1024** [comment]
@TQuy : Thanks. I'm always looking for collaboration. I hope to see your contribution in the future ^.^
