### ISSUE TITLE
VLSP 2016 shared task, With gold POS and chunking tags

### ISSUE THREAD

**Issue by TQuy** [undertheseanlp/NLP-Vietnamese-progress#6]
The no.1 should also be the no.1 in the board without gold POS and chunking tags with 95.33 % when using POS tag and Chunking tag
Ngan Dong 2018 "Attentive Neural Network for Named Entity Recognition in Vietnamese"

**Comment by rain1024** [comment]
It's updated. Thanks for your contribution :smile:
