### ISSUE TITLE
Chunk tagging pre-trained model

### ISSUE THREAD

**Issue by TQuy** [undertheseanlp/NLP-Vietnamese-progress#7]
I wonder why Underthesea chunk tagging doesn't work? I need a pretrained chunk tagging model for my undergraduate dissertation, which is about Named Entity Recognition, but I can't find any

**Comment by rain1024** [comment]
You can find repos here [chunking repo](https://github.com/undertheseanlp/chunking) and [ner repo](https://github.com/undertheseanlp/ner)
