### ISSUE TITLE
NER dataset

### ISSUE THREAD

**Issue by Crescentz** [undertheseanlp/NLP-Vietnamese-progress#8]
How get datasets of VLSP。
I had try to email vlsp.resources@gmail.com， but get no reply.
IS there any methods get NER datasets of Vietnamese

**Comment by rain1024** [comment]
Hi @Crescentz,

As far as I know, you can try email to huyenntm@hus.edu.vn (Ms. Huyen is administrator of VLSP Project)

Good luck.
