### ISSUE TITLE
Update 2020

### ISSUE THREAD

**Issue by ngoquanghuy99** [undertheseanlp/NLP-Vietnamese-progress#9]
Năm nay chưa cập nhật SOTA pretrained model hả anh?

**Comment by rain1024** [comment]
@ngoquanghuy99 Cho bài toán nào hả em?

**Comment by ngoquanghuy99** [comment]
> @ngoquanghuy99 Cho bài toán nào hả em?

Em để ý qua thấy năm nay có một vài pretrained language model cho kết quả SOTA với POS hay NER anh.
Bên VinAI có PhoBERT, bên FPT có viBERT.

**Comment by rain1024** [comment]
@ngoquanghuy99 Đúng rồi. Em có thể gửi merge request cho những kết quả mới nhất này nhé. Thanks em
